export interface CountryCode {
  code: string
  country: string
  flag: string
  maxLength: number
  popular?: boolean
}

// Popular countries for UAE-based business
export const popularCountries: CountryCode[] = [
  { code: '+971', country: 'UAE', flag: '🇦🇪', maxLength: 9, popular: true },
  { code: '+966', country: 'Saudi Arabia', flag: '🇸🇦', maxLength: 9, popular: true },
  { code: '+974', country: 'Qatar', flag: '🇶🇦', maxLength: 8, popular: true },
  { code: '+973', country: 'Bahrain', flag: '🇧🇭', maxLength: 8, popular: true },
  { code: '+968', country: 'Oman', flag: '🇴🇲', maxLength: 8, popular: true },
  { code: '+965', country: 'Kuwait', flag: '🇰🇼', maxLength: 8, popular: true },
  { code: '+91', country: 'India', flag: '🇮🇳', maxLength: 10, popular: true },
  { code: '+92', country: 'Pakistan', flag: '🇵🇰', maxLength: 10, popular: true },
  { code: '+880', country: 'Bangladesh', flag: '🇧🇩', maxLength: 10, popular: true },
  { code: '+63', country: 'Philippines', flag: '🇵🇭', maxLength: 10, popular: true },
  { code: '+44', country: 'United Kingdom', flag: '🇬🇧', maxLength: 10, popular: true },
  { code: '+1', country: 'USA', flag: '🇺🇸', maxLength: 10, popular: true },
]

export const allCountryCodes: CountryCode[] = [
  // Middle East & GCC
  { code: '+971', country: 'UAE', flag: '🇦🇪', maxLength: 9 },
  { code: '+966', country: 'Saudi Arabia', flag: '🇸🇦', maxLength: 9 },
  { code: '+965', country: 'Kuwait', flag: '🇰🇼', maxLength: 8 },
  { code: '+974', country: 'Qatar', flag: '🇶🇦', maxLength: 8 },
  { code: '+973', country: 'Bahrain', flag: '🇧🇭', maxLength: 8 },
  { code: '+968', country: 'Oman', flag: '🇴🇲', maxLength: 8 },
  { code: '+20', country: 'Egypt', flag: '🇪🇬', maxLength: 10 },
  { code: '+962', country: 'Jordan', flag: '🇯🇴', maxLength: 9 },
  { code: '+961', country: 'Lebanon', flag: '🇱🇧', maxLength: 8 },
  { code: '+964', country: 'Iraq', flag: '🇮🇶', maxLength: 10 },
  { code: '+963', country: 'Syria', flag: '🇸🇾', maxLength: 9 },
  { code: '+967', country: 'Yemen', flag: '🇾🇪', maxLength: 9 },
  { code: '+970', country: 'Palestine', flag: '🇵🇸', maxLength: 9 },
  
  // North America
  { code: '+1', country: 'USA', flag: '🇺🇸', maxLength: 10 },
  { code: '+1', country: 'Canada', flag: '🇨🇦', maxLength: 10 },
  { code: '+52', country: 'Mexico', flag: '🇲🇽', maxLength: 10 },
  
  // Europe
  { code: '+44', country: 'United Kingdom', flag: '🇬🇧', maxLength: 10 },
  { code: '+49', country: 'Germany', flag: '🇩🇪', maxLength: 11 },
  { code: '+33', country: 'France', flag: '🇫🇷', maxLength: 9 },
  { code: '+39', country: 'Italy', flag: '🇮🇹', maxLength: 10 },
  { code: '+34', country: 'Spain', flag: '🇪🇸', maxLength: 9 },
  { code: '+31', country: 'Netherlands', flag: '🇳🇱', maxLength: 9 },
  { code: '+32', country: 'Belgium', flag: '🇧🇪', maxLength: 9 },
  { code: '+41', country: 'Switzerland', flag: '🇨🇭', maxLength: 9 },
  { code: '+43', country: 'Austria', flag: '🇦🇹', maxLength: 11 },
  { code: '+46', country: 'Sweden', flag: '🇸🇪', maxLength: 9 },
  { code: '+47', country: 'Norway', flag: '🇳🇴', maxLength: 8 },
  { code: '+45', country: 'Denmark', flag: '🇩🇰', maxLength: 8 },
  { code: '+358', country: 'Finland', flag: '🇫🇮', maxLength: 10 },
  { code: '+48', country: 'Poland', flag: '🇵🇱', maxLength: 9 },
  { code: '+351', country: 'Portugal', flag: '🇵🇹', maxLength: 9 },
  { code: '+30', country: 'Greece', flag: '🇬🇷', maxLength: 10 },
  { code: '+353', country: 'Ireland', flag: '🇮🇪', maxLength: 9 },
  { code: '+420', country: 'Czech Republic', flag: '🇨🇿', maxLength: 9 },
  { code: '+7', country: 'Russia', flag: '🇷🇺', maxLength: 10 },
  { code: '+380', country: 'Ukraine', flag: '🇺🇦', maxLength: 9 },
  { code: '+90', country: 'Turkey', flag: '🇹🇷', maxLength: 10 },
  { code: '+36', country: 'Hungary', flag: '🇭🇺', maxLength: 9 },
  { code: '+40', country: 'Romania', flag: '🇷🇴', maxLength: 9 },
  { code: '+359', country: 'Bulgaria', flag: '🇧🇬', maxLength: 9 },
  { code: '+385', country: 'Croatia', flag: '🇭🇷', maxLength: 9 },
  { code: '+386', country: 'Slovenia', flag: '🇸🇮', maxLength: 8 },
  { code: '+421', country: 'Slovakia', flag: '🇸🇰', maxLength: 9 },
  { code: '+372', country: 'Estonia', flag: '🇪🇪', maxLength: 8 },
  { code: '+371', country: 'Latvia', flag: '🇱🇻', maxLength: 8 },
  { code: '+370', country: 'Lithuania', flag: '🇱🇹', maxLength: 8 },
  { code: '+373', country: 'Moldova', flag: '🇲🇩', maxLength: 8 },
  { code: '+377', country: 'Monaco', flag: '🇲🇨', maxLength: 8 },
  { code: '+354', country: 'Iceland', flag: '🇮🇸', maxLength: 7 },
  { code: '+352', country: 'Luxembourg', flag: '🇱🇺', maxLength: 9 },
  
  // Asia
  { code: '+91', country: 'India', flag: '🇮🇳', maxLength: 10 },
  { code: '+92', country: 'Pakistan', flag: '🇵🇰', maxLength: 10 },
  { code: '+880', country: 'Bangladesh', flag: '🇧🇩', maxLength: 10 },
  { code: '+86', country: 'China', flag: '🇨🇳', maxLength: 11 },
  { code: '+81', country: 'Japan', flag: '🇯🇵', maxLength: 10 },
  { code: '+82', country: 'South Korea', flag: '🇰🇷', maxLength: 10 },
  { code: '+65', country: 'Singapore', flag: '🇸🇬', maxLength: 8 },
  { code: '+60', country: 'Malaysia', flag: '🇲🇾', maxLength: 10 },
  { code: '+66', country: 'Thailand', flag: '🇹🇭', maxLength: 9 },
  { code: '+62', country: 'Indonesia', flag: '🇮🇩', maxLength: 11 },
  { code: '+63', country: 'Philippines', flag: '🇵🇭', maxLength: 10 },
  { code: '+84', country: 'Vietnam', flag: '🇻🇳', maxLength: 9 },
  { code: '+852', country: 'Hong Kong', flag: '🇭🇰', maxLength: 8 },
  { code: '+886', country: 'Taiwan', flag: '🇹🇼', maxLength: 9 },
  { code: '+977', country: 'Nepal', flag: '🇳🇵', maxLength: 10 },
  { code: '+94', country: 'Sri Lanka', flag: '🇱🇰', maxLength: 9 },
  { code: '+98', country: 'Iran', flag: '🇮🇷', maxLength: 10 },
  { code: '+93', country: 'Afghanistan', flag: '🇦🇫', maxLength: 9 },
  { code: '+855', country: 'Cambodia', flag: '🇰🇭', maxLength: 9 },
  { code: '+856', country: 'Laos', flag: '🇱🇦', maxLength: 9 },
  { code: '+95', country: 'Myanmar', flag: '🇲🇲', maxLength: 9 },
  { code: '+976', country: 'Mongolia', flag: '🇲🇳', maxLength: 8 },
  { code: '+960', country: 'Maldives', flag: '🇲🇻', maxLength: 7 },
  { code: '+975', country: 'Bhutan', flag: '🇧🇹', maxLength: 8 },
  { code: '+673', country: 'Brunei', flag: '🇧🇳', maxLength: 7 },
  { code: '+670', country: 'Timor-Leste', flag: '🇹🇱', maxLength: 8 },
  
  // Oceania
  { code: '+61', country: 'Australia', flag: '🇦🇺', maxLength: 9 },
  { code: '+64', country: 'New Zealand', flag: '🇳🇿', maxLength: 9 },
  { code: '+679', country: 'Fiji', flag: '🇫🇯', maxLength: 7 },
  { code: '+675', country: 'Papua New Guinea', flag: '🇵🇬', maxLength: 8 },
  { code: '+685', country: 'Samoa', flag: '🇼🇸', maxLength: 7 },
  { code: '+676', country: 'Tonga', flag: '🇹🇴', maxLength: 7 },
  
  // Africa
  { code: '+27', country: 'South Africa', flag: '🇿🇦', maxLength: 9 },
  { code: '+234', country: 'Nigeria', flag: '🇳🇬', maxLength: 10 },
  { code: '+254', country: 'Kenya', flag: '🇰🇪', maxLength: 10 },
  { code: '+233', country: 'Ghana', flag: '🇬🇭', maxLength: 9 },
  { code: '+212', country: 'Morocco', flag: '🇲🇦', maxLength: 9 },
  { code: '+213', country: 'Algeria', flag: '🇩🇿', maxLength: 9 },
  { code: '+216', country: 'Tunisia', flag: '🇹🇳', maxLength: 8 },
  { code: '+218', country: 'Libya', flag: '🇱🇾', maxLength: 9 },
  { code: '+249', country: 'Sudan', flag: '🇸🇩', maxLength: 9 },
  { code: '+251', country: 'Ethiopia', flag: '🇪🇹', maxLength: 9 },
  { code: '+256', country: 'Uganda', flag: '🇺🇬', maxLength: 9 },
  { code: '+255', country: 'Tanzania', flag: '🇹🇿', maxLength: 9 },
  { code: '+260', country: 'Zambia', flag: '🇿🇲', maxLength: 9 },
  { code: '+263', country: 'Zimbabwe', flag: '🇿🇼', maxLength: 9 },
  { code: '+265', country: 'Malawi', flag: '🇲🇼', maxLength: 9 },
  { code: '+258', country: 'Mozambique', flag: '🇲🇿', maxLength: 9 },
  { code: '+264', country: 'Namibia', flag: '🇳🇦', maxLength: 9 },
  { code: '+267', country: 'Botswana', flag: '🇧🇼', maxLength: 8 },
  { code: '+266', country: 'Lesotho', flag: '🇱🇸', maxLength: 8 },
  { code: '+268', country: 'Eswatini', flag: '🇸🇿', maxLength: 8 },
  { code: '+250', country: 'Rwanda', flag: '🇷🇼', maxLength: 9 },
  { code: '+257', country: 'Burundi', flag: '🇧🇮', maxLength: 8 },
  { code: '+252', country: 'Somalia', flag: '🇸🇴', maxLength: 8 },
  { code: '+253', country: 'Djibouti', flag: '🇩🇯', maxLength: 8 },
  { code: '+225', country: 'Ivory Coast', flag: '🇨🇮', maxLength: 8 },
  { code: '+226', country: 'Burkina Faso', flag: '🇧🇫', maxLength: 8 },
  { code: '+221', country: 'Senegal', flag: '🇸🇳', maxLength: 9 },
  { code: '+223', country: 'Mali', flag: '🇲🇱', maxLength: 8 },
  { code: '+227', country: 'Niger', flag: '🇳🇪', maxLength: 8 },
  { code: '+228', country: 'Togo', flag: '🇹🇬', maxLength: 8 },
  { code: '+229', country: 'Benin', flag: '🇧🇯', maxLength: 8 },
  { code: '+230', country: 'Mauritius', flag: '🇲🇺', maxLength: 8 },
  { code: '+231', country: 'Liberia', flag: '🇱🇷', maxLength: 8 },
  { code: '+232', country: 'Sierra Leone', flag: '🇸🇱', maxLength: 8 },
  { code: '+235', country: 'Chad', flag: '🇹🇩', maxLength: 8 },
  { code: '+236', country: 'Central African Republic', flag: '🇨🇫', maxLength: 8 },
  { code: '+237', country: 'Cameroon', flag: '🇨🇲', maxLength: 9 },
  { code: '+238', country: 'Cape Verde', flag: '🇨🇻', maxLength: 7 },
  { code: '+240', country: 'Equatorial Guinea', flag: '🇬🇶', maxLength: 9 },
  { code: '+241', country: 'Gabon', flag: '🇬🇦', maxLength: 7 },
  { code: '+242', country: 'Republic of Congo', flag: '🇨🇬', maxLength: 9 },
  { code: '+243', country: 'DR Congo', flag: '🇨🇩', maxLength: 9 },
  { code: '+244', country: 'Angola', flag: '🇦🇴', maxLength: 9 },
  { code: '+245', country: 'Guinea-Bissau', flag: '🇬🇼', maxLength: 7 },
  { code: '+246', country: 'Diego Garcia', flag: '🇮🇴', maxLength: 7 },
  { code: '+248', country: 'Seychelles', flag: '🇸🇨', maxLength: 7 },
  { code: '+261', country: 'Madagascar', flag: '🇲🇬', maxLength: 9 },
  { code: '+262', country: 'Reunion', flag: '🇷🇪', maxLength: 9 },
  { code: '+269', country: 'Comoros', flag: '🇰🇲', maxLength: 7 },
  { code: '+291', country: 'Eritrea', flag: '🇪🇷', maxLength: 7 },
  
  // South America
  { code: '+55', country: 'Brazil', flag: '🇧🇷', maxLength: 11 },
  { code: '+54', country: 'Argentina', flag: '🇦🇷', maxLength: 10 },
  { code: '+56', country: 'Chile', flag: '🇨🇱', maxLength: 9 },
  { code: '+57', country: 'Colombia', flag: '🇨🇴', maxLength: 10 },
  { code: '+51', country: 'Peru', flag: '🇵🇪', maxLength: 9 },
  { code: '+58', country: 'Venezuela', flag: '🇻🇪', maxLength: 10 },
  { code: '+593', country: 'Ecuador', flag: '🇪🇨', maxLength: 9 },
  { code: '+591', country: 'Bolivia', flag: '🇧🇴', maxLength: 8 },
  { code: '+595', country: 'Paraguay', flag: '🇵🇾', maxLength: 9 },
  { code: '+598', country: 'Uruguay', flag: '🇺🇾', maxLength: 8 },
  { code: '+592', country: 'Guyana', flag: '🇬🇾', maxLength: 7 },
  { code: '+597', country: 'Suriname', flag: '🇸🇷', maxLength: 7 },
  { code: '+594', country: 'French Guiana', flag: '🇬🇫', maxLength: 9 },
  
  // Central America & Caribbean
  { code: '+503', country: 'El Salvador', flag: '🇸🇻', maxLength: 8 },
  { code: '+502', country: 'Guatemala', flag: '🇬🇹', maxLength: 8 },
  { code: '+504', country: 'Honduras', flag: '🇭🇳', maxLength: 8 },
  { code: '+505', country: 'Nicaragua', flag: '🇳🇮', maxLength: 8 },
  { code: '+506', country: 'Costa Rica', flag: '🇨🇷', maxLength: 8 },
  { code: '+507', country: 'Panama', flag: '🇵🇦', maxLength: 8 },
  { code: '+509', country: 'Haiti', flag: '🇭🇹', maxLength: 8 },
  { code: '+53', country: 'Cuba', flag: '🇨🇺', maxLength: 8 },
  { code: '+1', country: 'Jamaica', flag: '🇯🇲', maxLength: 10 },
  { code: '+1', country: 'Puerto Rico', flag: '🇵🇷', maxLength: 10 },
  { code: '+1', country: 'Dominican Republic', flag: '🇩🇴', maxLength: 10 },
  { code: '+1', country: 'Trinidad and Tobago', flag: '🇹🇹', maxLength: 10 },
  { code: '+1', country: 'Bahamas', flag: '🇧🇸', maxLength: 10 },
  { code: '+1', country: 'Barbados', flag: '🇧🇧', maxLength: 10 },
  { code: '+501', country: 'Belize', flag: '🇧🇿', maxLength: 7 },
]

// Get other countries (excluding popular ones)
export const otherCountries: CountryCode[] = allCountryCodes.filter(
  country => !popularCountries.some(
    popular => popular.code === country.code && popular.country === country.country
  )
)

// Export all countries (for backwards compatibility)
export const countryCodes: CountryCode[] = allCountryCodes
